### default observation parameters needed for a LFOA simulation
object : configuration
alias : OBS
name : LFOA_default_configuration
description : default parameters needed for a LFOA simulation
status: experimental

packages :
- LFOA

yamls :
- LFOA.yaml
- LFOA_SBIG.yaml

properties :
  instrument: LFOA
  airmass : 1.2
  declination : +30
  hour_angle : 0
  pupil_angle : 0
  dit : 60
  ndit : 1
  filter_name : V
  sky :
    bg_mag : 19.5
    filter_name : V

---

### default simulation parameters needed for a LFAO simulation
object : simulation
alias : SIM
name : LFAO_simulation_paramters
description : RC simulation paramters

properties :
  random :
    seed : 9001

  spectral :
    wave_min : 0.3
    wave_mid : 0.55
    wave_max : 1.0

  computing :
    preload_field_of_view : False
