### default observation parameters needed for an OSIRIS simulation

object : configuration
alias : OBS
name : OSIRIS_default_configuration
description : default parameters needed for a OSIRIS simulation
date_created: 2022-03-02
date_modified: 2022-03-02
changes:
  - 2022-03-02 (KL) Created file based on METIS default.yaml


packages :
- LaPalma
- GTC
- MAAT
- OSIRIS

yamls :
- LaPalma.yaml
- GTC.yaml
- OSIRIS.yaml

properties :
  modes : ["IMG"]
  airmass : 1.2
  declination : -30
  hour_angle : 0
  pupil_angle : 0
  dit : 60
  ndit : 1
  grating_name : None

mode_yamls :
- object : instrument
  alias: OBS
  name : IMG
  description : "OSIRIS imaging mode"
  properties:
    filter_name : sdss_r
    grating_name : unity

- object : instrument
  alias: OBS
  name : LSS
  description : "OSIRIS Long-Slit mode"
  properties:
    filter_name : None
    grating_name : None

- object : instrument
  alias: OBS
  name : MAAT
  description : "OSIRIS IFU (MAAT) mode"
  yamls :
    - MAAT.yaml
  properties:
    filter_name : None
    grating_name : None


---
### default simulation parameters needed for a METIS simulation
object: simulation
alias: SIM
name: OSIRIS_simulation_parameters
description: RC simulation parameters which need to change for a OSIRIS run

properties:
  random:
    seed: None                         # 9001

  spectral:   # in [um]
    wave_min: 0.3001
    wave_mid: 0.6
    wave_max: 1.0
    spectral_bin_width: 0.00001       # 0.1 Angstrom

  computing:
    spline_order: 1
    preload_field_of_views: True

