"""
Configuration file for Sphinx and ReadTheDocs

This file originally lived in docs/source.
It has been moved into the top level so that all package docs are accessible to
sphinx
"""


#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Instrument Reference Database documentation build configuration file, created by
# sphinx-quickstart on Fri Jul 12 13:46:11 2019.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# sys.path.insert(0, os.path.abspath('.'))

import sys
import os
from pathlib import Path

sys.path.insert(0, os.path.abspath('/'))
sys.path.insert(0, os.path.abspath('docs'))

# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'nbsphinx',
    'sphinx.ext.intersphinx',
    'sphinx.ext.todo',
    'sphinx.ext.coverage',
    'sphinx.ext.mathjax',
    'sphinx.ext.viewcode',
    # 'matplotlib.sphinxext.plot_directive',
    # 'numpydoc',
    # 'sphinx.ext.autodoc',
    # 'jupyter_sphinx.execute',
    # 'sphinxcontrib.apidoc',
]

# numpydoc settings
numpydoc_show_class_members = False

# apidoc settings
# apidoc_module_dir = os.path.abspath('irdb/')
# apidoc_output_dir = 'docs/source/reference'
# apidoc_separate_modules = True
# apidoc_excluded_paths = ["tests/", "docs/"]

# nbsphinx settings
nbsphinx_allow_errors = True
nbsphinx_execute = "never"

# add_hidden_cell_to_ipynb_files()

def add_hidden_cell_to_ipynb_files():
    import glob
    old_string = '''"cells": ['''
    new_string = '''"cells": [
  {
    "cell_type": "code",
    "execution_count": null,
    "metadata": { "nbsphinx": "hidden" },
    "outputs": [],
    "source": [
      "import os, scopesim as sim",
      "if os.environ.get(\"READTHEDOCS\") == \"True\" or \"F:\" in os.getcwd():",
      "    sim.rc.__config__[\"!SIM.file.local_packages_path\"] = os.path.abspath(\"../../../\")",
    ]
  },'''
    paths = glob.glob("./**/*.ipynb", recursive=True)
    for path in paths:
        with open(path, "r+") as f:
            contents = f.read()
            # check if the hidden cell has already been added to notebook
            if 'os.environ.get("READTHEDOCS")' not in contents:
                contents = contents.replace(old_string, new_string)
                f.seek(0)
                f.write(contents)


# add_hidden_cell_to_ipynb_files()


def remove_inst_pkgs_symlink():
    """Remove inst_pkgs symlinks."""
    for path in list(Path(".").rglob('inst_pkgs')):
        if path.is_symlink():
            path.unlink()


remove_inst_pkgs_symlink()

# Matplotlib plot directive config parameters
plot_html_show_source_link = False

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = 'Instrument Reference Database'
copyright = '2019, A*Vienna Software Team'
author = 'Kieran Leschinski, Oliver Czoske'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = '0'
# The full version, including alpha/beta/rc tags.
release = '1'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = None

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = []

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'


# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
# html_theme = 'alabaster'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
html_theme_options = {"body_max_width": "900px"}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['docs/source/_static']      # 'METIS/docs/example_notebooks'
html_favicon = 'docs/source/_static/logos/T_favicon.png'


# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# This is required for the alabaster theme
# refs: http://alabaster.readthedocs.io/en/latest/installation.html#sidebars
# html_sidebars = {
#     '**': [
#         'relations.html',  # needs 'show_related': True theme option to display
#         'searchbox.html',
#     ]
# }


# -- Options for HTMLHelp output ------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'IRDB'


# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',

    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'InstrumentReferenceDatabase.tex', 'Instrument Reference Database Documentation',
     'Kieran Leschinski, Oliver Czoske', 'manual'),
]


# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'InstrumentReferenceDatabase', 'Instrument Reference Database Documentation',
     [author], 1)
]


# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'InstrumentReferenceDatabase', 'Instrument Reference Database Documentation',
     author, 'InstrumentReferenceDatabase', 'One line description of project.',
     'Miscellaneous'),
]




# Example configuration for intersphinx: refer to the Python standard library.
intersphinx_mapping = {'python': ('http://docs.python.org/', None),
                       'numpy': ('http://docs.scipy.org/doc/numpy/', None),
                       'scipy': ('http://docs.scipy.org/doc/scipy/reference/', None),
                       'matplotlib': ('http://matplotlib.org/', None),
                       'astropy': ('http://docs.astropy.org/en/stable/', None),
                       'synphot': ('https://synphot.readthedocs.io/en/latest/', None),
                       'scopesim_templates': ('https://scopesim_templates.readthedocs.io/en/latest/', None),
                       'pyckles': ('https://pyckles.readthedocs.io/en/latest/', None),
                       'anisocado': ('https://anisocado.readthedocs.io/en/latest/', None),
                       }


# -- Options for todo extension ----------------------------------------------

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = True
