"""
Configuration file for Sphinx and ReadTheDocs

This file originally lived in docs/source.
It has been moved into the top level so that all package docs are accessible to
sphinx
"""


#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Instrument Reference Database documentation build configuration file, created by
# sphinx-quickstart on Fri Jul 12 13:46:11 2019.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# sys.path.insert(0, os.path.abspath('.'))

import sys
import os
from pathlib import Path

sys.path.insert(0, os.path.abspath('/'))
sys.path.insert(0, os.path.abspath('docs'))

# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.intersphinx',
    'sphinx.ext.todo',
    'sphinx.ext.coverage',
    'sphinx.ext.mathjax',
    'sphinx.ext.viewcode',
    'sphinx_copybutton',
    'myst_nb',
]

# numpydoc settings
numpydoc_show_class_members = False



def remove_inst_pkgs_symlink():
    """Remove inst_pkgs symlinks."""
    for path in list(Path(".").rglob('inst_pkgs')):
        if path.is_symlink():
            path.unlink()


remove_inst_pkgs_symlink()

# Matplotlib plot directive config parameters
plot_html_show_source_link = False

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

source_suffix = {
    ".rst": "restructuredtext",
    ".ipynb": "myst-nb",
    ".myst": "myst-nb",
    ".md": "myst-nb",
}
source_encoding = 'utf-8'


# MyST NB stuff
nb_execution_timeout = 6  # [s]
nb_execution_mode = "force"
nb_execution_excludepatterns = [
    "METIS/docs/example_notebooks/LSS*",
    "METIS/docs/example_notebooks/IFU*",
    "MICADO/**"
]


# The master toctree document.
master_doc = 'index'

# General information about the project.
project = 'Instrument Reference Database'
copyright = '2024, A*Vienna Software Team'
author = 'Kieran Leschinski, Oliver Czoske'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = '0'
# The full version, including alpha/beta/rc tags.
release = '1'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = None

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = []

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'


# -- Options for HTML output ----------------------------------------------

html_theme = "sphinx_book_theme"
html_theme_options = {
    "repository_url": "https://github.com/AstarVienna/irdb",
    "use_repository_button": True,
    "use_download_button": True,
    "home_page_in_toc": True,
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['docs/source/_static']      # 'METIS/docs/example_notebooks'
html_logo = 'docs/source/_static/logos/T_favicon.png'
html_title = "IRDB"


# Add local templates path to modify autosummary templates
#templates_path = ['_templates']

# Static files to copy after template files
html_static_path = ['_static']
html_sidebars = {
    "**": [
        "navbar-logo.html",
        "search-field.html",
        "sbt-sidebar-nav.html",
    ]
}
html_sourcelink_suffix = ""

# -- Options for HTMLHelp output ------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'IRDB'


# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',

    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'InstrumentReferenceDatabase.tex', 'Instrument Reference Database Documentation',
     'Kieran Leschinski, Oliver Czoske', 'manual'),
]


# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'InstrumentReferenceDatabase', 'Instrument Reference Database Documentation',
     [author], 1)
]


# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'InstrumentReferenceDatabase', 'Instrument Reference Database Documentation',
     author, 'InstrumentReferenceDatabase', 'One line description of project.',
     'Miscellaneous'),
]




# Example configuration for intersphinx: refer to the Python standard library.
intersphinx_mapping = {'python': ('http://docs.python.org/', None),
                       'numpy': ('http://docs.scipy.org/doc/numpy/', None),
                       'scipy': ('http://docs.scipy.org/doc/scipy/reference/', None),
                       'matplotlib': ('http://matplotlib.org/', None),
                       'astropy': ('http://docs.astropy.org/en/stable/', None),
                       'synphot': ('https://synphot.readthedocs.io/en/latest/', None),
                       'scopesim_templates': ('https://scopesim_templates.readthedocs.io/en/latest/', None),
                       'pyckles': ('https://pyckles.readthedocs.io/en/latest/', None),
                       'anisocado': ('https://anisocado.readthedocs.io/en/latest/', None),
                       }


# -- Options for todo extension ----------------------------------------------

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = True
