### default observation parameters needed for a METIS simulation

object : configuration
alias : OBS
name : METIS_default_configuration
description : default parameters needed for a METIS simulation

packages :
  - Armazones
  - ELT
  - METIS

yamls :
  - Armazones.yaml
  - ELT.yaml
  - METIS.yaml

properties :
  modes : ["img_lm"]
  airmass : 1.2
  declination : -30
  hour_angle : 0
  pupil_angle : 0
  dit : 1
  ndit : 1

mode_yamls :
  - object : observation
    alias : OBS
    name: img_lm
    description : "METIS LM-band imaging"
    yamls:
      - METIS_IMG_LM.yaml
      - METIS_DET_IMG_LM.yaml
    properties :
      filter_name : L

  - name: img_n
    yamls:
      - METIS_IMG_N.yaml
      - METIS_DET_IMG_N_GeoSnap.yaml

  - name: lss_lm
    yamls:
      - METIS_LSS_LM.yaml
      - METIS_DET_IMG_LM.yaml

  - name: lss_n
    yamls:
      - METIS_LSS_N.yaml
      - METIS_DET_IMG_N_GeoSnap.yaml

  - name: lms
    yamls:
      - METIS_LMS.yaml
      - METIS_DET_IFU.yaml

  - name: lms_extended
    yamls:
      - METIS_LMS_ext.yaml
      - METIS_DET_IFU.yaml

ignore_effects :
  - armazones_atmo_dispersion
  - scope_vibration
  - detector_linearity



---
### default simulation parameters needed for a METIS simulation
object : simulation
alias : SIM
name : METIS_simulation_parameters
description : RC simulation parameters which need to change for a METIS run

properties :
  random :
    seed : 9001

  spectral :
    wave_min : 3.0
    wave_mid : 10.5
    wave_max : 18.0
