---
### FORS package metadata
alias: PKG
name: FORS
description: NOT YET FUNCTIONAL PLACEHOLDER
status: concept
date_modified: 2024-12-12
changes:
  - 2024-12-12 (FH) initial creation

packages:
  - FORS

yamls:
  - FORS.yaml
