# name: micado_sci_default
# description: default observation parameters for MICADO-Sci
# author : Kieran Leschinski
# date_created : 2020-07-09
# date_modified : 2020-08-17

object : configuration
alias : OBS
name : MICADO_sci_default_configuration
description : default parameters needed for a MICADO-Sci simulation

packages :
- Armazones
- ELT
- MAORY
- MICADO
- MICADO_Sci

yamls :
- MICADO_Sci.yaml
- MICADO_Sci_detector.yaml

properties :
  modes : ["SCAO", "IMG_4mas"]
  dit : 60
  ndit : 1
  airmass : 1.2
  pupil_angle : 0

mode_yamls :
- object : instrument
  alias : INST
  name : SCAO
  description : "SCAO optical system"
  yamls :
  - MICADO_Sci_SCAO.yaml

- object : instrument
  alias : INST
  name : MCAO
  description : "MCAO optical system"
  yamls :
  - MICADO_Sci_MCAO.yaml

- object : instrument
  alias : INST
  name : IMG_4mas
  description : "wide-field imager  : 4mas/pix"
  properties :
    filter_name : Ks
    pixel_scale : 0.004         # arcsec / pixel
    plate_scale : 0.26666666666 # arcsec / mm

- object : instrument
  alias : INST
  name : IMG_1.5mas
  description : "zoom imager : 1.5mas/pix"
  properties :
    filter_name : Ks
    pixel_scale : 0.0015    # arcsec / pixel
    plate_scale : 0.1       # arcsec / mm

- object : instrument
  alias : INST
  name : SPEC
  description : "Spectroscopy"
  yamls :
    - MICADO_Sci_SPEC.yaml
  properties :
    filter_name : Spec_HK
    pixel_scale : 0.004         # arcsec / pixel
    plate_scale : 0.26666666666 # arcsec / mm


---
### default simulation parameters needed for a MICADO simulation
object : simulation
alias : SIM
name : MICADO_sci_simulation_paramters
description : RC simulation paramters which need to change for a MICADO-Sci run

properties :
  random :
    seed : 9001

  spectral :
    wave_min : 0.7
    wave_mid : 1.6
    wave_max : 2.5
    spectral_resolution : 0.001

  computing :
    preload_field_of_view : True
