### default configuration for HST/WFC3 observations
# source : https://hst-docs.stsci.edu/display/WFC3IHB/2.1+Optical+Design+and+Detectors
# all spectral curves found on the stsynphot site
# https://stsynphot.readthedocs.io/en/latest/stsynphot/data_hst.html

object : configuration
alias : OBS
name : HST_WFC3_default_config
description : defatult configuration for HST WFC3 UVIS and NIR imaging

packages:
- HST
- WFC3

yamls:
- HST.yaml
- WFC3.yaml

mode_yamls:
-   name: IR_channel
    description: The NIR imaging channel
    yamls:
    - WFC3_IR.yaml
    - WFC3_IR_DET.yaml

-   name: UVIS_channel
    description: The UV and Visual imaging channel
    yamls:
    - WFC3_UVIS.yaml
    - WFC3_UVIS_DET.yaml

properties:
  modes: [IR_channel]
  filter_name: F160W
  dit: 60
  ndit: 1


---

# default simulation parameters
object : simulation
alias : SIM
name : WFC3_simulation_paramters
description : RC simulation paramters which need to change for a WFC3

properties :
  random :
    seed : 9001

  spectral :
    wave_min : 0.8
    wave_mid : 1.3
    wave_max : 1.8