### default configuration for HST/WFC3 observations
# source : https://hst-docs.stsci.edu/display/WFC3IHB/2.1+Optical+Design+and+Detectors
# all spectral curves found on the stsynphot site
# https://stsynphot.readthedocs.io/en/latest/stsynphot/data_hst.html

---
### WFC3 package metadata
alias : PKG
name : HST_WFC3_default_config
description : defatult configuration for HST WFC3 UVIS and NIR imaging
status: experimental
date_modified: 2024-12-12
changes:
  - 2019-11-19 (KL) initial creation
  - 2020-04-22 (KL) modes is now a list
  - 2024-11-19 (FH) add status keywords
  - 2024-12-12 (FH) restructure default OBS properties, add PKG alias

packages:
  - HST
  - WFC3

yamls:
  - HST.yaml
  - WFC3.yaml

mode_yamls:
  - name: IR_channel
    description: The NIR imaging channel
    yamls:
      - WFC3_IR.yaml
      - WFC3_IR_DET.yaml

  - name: UVIS_channel
    description: The UV and Visual imaging channel
    yamls:
      - WFC3_UVIS.yaml
      - WFC3_UVIS_DET.yaml

---
### default observation parameters needed for a WFC3 simulation
alias: OBS
properties:
  modes: [IR_channel]
  filter_name: F160W
  dit: 60  # [s]
  ndit: 1

---
### default simulation parameters needed for a WFC3 simulation
alias: SIM
properties:
  random:
    seed: 9001

  spectral:
    wave_min: 0.8  # [um]
    wave_mid: 1.3  # [um]
    wave_max: 1.8  # [um]
