# Default configuration for the Vienna Little Telescope

object : configuration
alias : OBS
name : ViLT_default_configuration
description : Vienna Little Telescope configuration
status: experimental

packages :
  - LFOA
  - ViennaLT

yamls :
  - ViennaLT.yaml
  - ViLT_PL16803.yaml

properties :
  airmass : 1.2
  declination : +30
  hour_angle : 0
  pupil_angle : 0
  dit : 60
  ndit : 1
  filter_name : V
  sky :
    bg_mag : 19.
    filter_name : V

---

## default simulation parameters needed for a simulation
object : simulation
alias : SIM
name : ViLT_simulation_paramters
description : RC simulation paramters

properties :
  random :
    seed : 9001

  spectral :
    wave_min : 0.3
    wave_mid : 0.55
    wave_max : 1.0

  computing :
    preload_field_of_view : False





