### default observation parameters needed for a MOSAIC simulation
object : configuration
alias : OBS
name : MOSAIC_default_configuration
description : default parameters needed for a MOSAIC simulation

packages :
- Armazones
- ELT
- MOSAIC

yamls :
- Armazones.yaml
- ELT.yaml

properties :
  modes : ["MOS-NIR-LR-H"]
  airmass : 1.2
  declination : -30
  hour_angle : 0
  pupil_angle : 0
  dit : 60
  ndit : 1
  instrument : MOSAIC
  ra : 0.0
  dec : 0.0
  psf_fwhm : 0.2


mode_yamls :
- object : instrument
  alias: OBS
  name : "MOS-NIR-LR-H"
  description : "MVP system for a single MOSAIC config"
  yamls :
  - MOSAIC-MOS-NIR-LR-H.yaml
  - MOSAIC_H_DET.yaml


---
### default simulation parameters needed for a MICADO simulation
object : simulation
alias : SIM
name : MICADO_simulation_paramters
description : RC simulation paramters which need to change for a MICADO run

properties :
  random :
    seed : None

  spectral :
    wave_min : 0.8
    wave_mid : 1.3
    wave_max : 1.75

  computing :
    preload_field_of_view : True
