### default observation parameters needed for a MOSAIC simulation
object : configuration
alias : OBS
name : MOSAIC_default_configuration
description : default parameters needed for a MOSAIC simulation
needs_scopesim: "v0.10.0b4"
date_modified: 2025-07-17

packages :
  - Armazones
  - ELT
  - MOSAIC

yamls :
  - Armazones.yaml
  - ELT.yaml

properties :
  instrument: "MOSAIC"
  modes : ["MOS-LR-R"]     # default mode
  airmass : 1.2
  declination : -30
  hour_angle : 0
  pupil_angle : 0
  exptime: 60
  dit : 60
  ndit : 1
  ra : 0.0
  dec : 0.0
  psf_fwhm : 0.2
  include_fibres : True


mode_yamls :
  - object: observation
    alias: OBS
    name: MOS-LR-B
    description: "MOSAIC visual low resolution B band"
    status: development
    yamls:
      - MOSAIC_VIS.yaml
      - MOSAIC_DET_VIS_smpl.yaml
    properties:
      ins_mode: MOS-LR-B    # use as FITS header keyword
      ter_file:   TER_sys_MOS-LR-B.dat
      # psf_file: PSF_GLAO_R.fits
      trace_file: TRACE_MOS-LR-B.fits
      dispersion: 1.9e-5      # um/pixel on the output detector

  - object: observation
    alias: OBS
    name: MOS-HR-B1
    description: "MOSAIC visual high resolution B1 band"
    status: development
    yamls:
      - MOSAIC_VIS.yaml
      - MOSAIC_DET_VIS_smpl.yaml
    properties:
      ins_mode: MOS-HR-B1
      ter_file:   TER_sys_MOS-HR-B1.dat
      trace_file: TRACE_MOS-HR-B1.fits
      dispersion: 6.5e-6    # um/pixel on detector

  - object: observation
    alias: OBS
    name: MOS-HR-B2
    description: "MOSAIC visual high resolution B2 band"
    status: development
    yamls:
      - MOSAIC_VIS.yaml
      - MOSAIC_DET_VIS_smpl.yaml
    properties:
      ins_mode: MOS-HR-B2
      ter_file:   TER_sys_MOS-HR-B2.dat
      trace_file: TRACE_MOS-HR-B2.fits
      dispersion: 5e-6    # um/pixel on detector

  - object: observation
    alias: OBS
    name: MOS-LR-R
    description: "MOSAIC visual low resolution R band"
    status: development
    yamls:
      - MOSAIC_VIS.yaml
      - MOSAIC_DET_VIS_smpl.yaml
    properties:
      ins_mode: MOS-LR-R    # use as FITS header keyword
      ter_file:   TER_sys_MOS-LR-R.dat
      # psf_file: PSF_GLAO_R.fits
      trace_file: TRACE_MOS-LR-R.fits
      dispersion: 3e-5      # um/pixel on the output detector

  - object: observation
    alias: OBS
    name: MOS-HR-R1
    description: "MOSAIC visual high resolution R1 band"
    status: development
    yamls:
      - MOSAIC_VIS.yaml
      - MOSAIC_DET_VIS_smpl.yaml
    properties:
      ins_mode: MOS-HR-R1
      ter_file:   TER_sys_MOS-HR-R1.dat
      trace_file: TRACE_MOS-HR-R1.fits
      dispersion: 8e-6    # um/pixel on detector

  - object: observation
    alias: OBS
    name: MOS-HR-R2
    description: "MOSAIC visual high resolution R2 band"
    status: development
    yamls:
      - MOSAIC_VIS.yaml
      - MOSAIC_DET_VIS_smpl.yaml
    properties:
      ins_mode: MOS-HR-R2
      ter_file:   TER_sys_MOS-HR-R2.dat
      trace_file: TRACE_MOS-HR-R2.fits
      dispersion: 1e-5    # um/pixel on detector

  - object : instrument
    alias: OBS
    name: MOS-LR-J
    description: "MOSAIC near-infrared low resolution J band"
    status: development
    yamls:
      - MOSAIC_NIR.yaml
      - MOSAIC_DET_NIR.yaml
    properties:
      ins_mode: MOS-LR-J
      fibre_ter_file: TER_mos_LR-J.dat
      spec_ter_file:  TER_spec_LR-J.dat
      trace_file: TRACE_MOS-LR-J.fits
      dispersion: 9.5e-5    # um/pixel on detector

  - object : instrument
    alias: OBS
    name : MOS-LR-H
    description : "MOSAIC near-infrared low resolution H band"
    status: development
    yamls :
      - MOSAIC_NIR.yaml
      - MOSAIC_DET_NIR.yaml
    properties:
      ins_mode: MOS-LR-H
      fibre_ter_file: TER_mos_LR-H.dat
      spec_ter_file:  TER_spec_LR-H.dat
      trace_file: TRACE_MOS-LR-H.fits
      dispersion: 9.e-5     # um/pixel on detector

  - object : instrument
    alias: OBS
    name : MOS-HR-H
    description : "MOSAIC near-infrared high resolution H band"
    status: development
    yamls :
      - MOSAIC_NIR.yaml
      - MOSAIC_DET_NIR.yaml
    properties:
      ins_mode: MOS-HR-H
      fibre_ter_file: TER_mos_HR-H.dat
      spec_ter_file:  TER_spec_HR-H.dat
      trace_file: TRACE_MOS-HR-H.fits
      dispersion: 2.4e-5    # um/pixel on detector

  - object : instrument
    alias: OBS
    name : mIFU-LR-J
    description : "MOSAIC near-infrared low resolution J band"
    status: development
    yamls :
      - MOSAIC_NIR.yaml
      - MOSAIC_DET_NIR.yaml
    properties:
      ins_mode: mIFU-LR-J
      fibre_ter_file: TER_mIFU_LR-J.dat
      spec_ter_file:  TER_spec_LR-J.dat
      trace_file: TRACE_mIFU-LR-J.fits
      dispersion: 9.5e-5    # um/pixel on detector

  - object : instrument
    alias: OBS
    name : mIFU-LR-H
    description : "MOSAIC near-infrared low resolution H band"
    status: development
    yamls :
      - MOSAIC_NIR.yaml
      - MOSAIC_DET_NIR.yaml
    properties:
      ins_mode: mIFU-LR-H
      fibre_ter_file: TER_mIFU_LR-H.dat
      spec_ter_file:  TER_spec_LR-H.dat
      trace_file: TRACE_mIFU-LR-H.fits
      dispersion: 9.e-5     # um/pixel on detector

  - object : instrument
    alias: OBS
    name : mIFU-HR-H
    description : "MOSAIC near-infrared high resolution H band"
    status: development
    yamls :
      - MOSAIC_NIR.yaml
      - MOSAIC_DET_NIR.yaml
    properties:
      ins_mode: mIFU-HR-H
      fibre_ter_file: TER_mIFU_HR-H.dat
      spec_ter_file:  TER_spec_NIR_HR_H.dat
      trace_file: TRACE_mIFU_NIR-HR-H.fits
      dispersion: 2.4e-5    # um/pixel on detector



---
### default simulation parameters needed for a MOSAIC simulation
object : simulation
alias : SIM
name : MOSAIC_simulation_parameters
description : RC simulation paramters which need to change for a MOSAIC run

properties :
  random :
    seed : None

  spectral :
    wave_min : 0.35
    wave_mid : 1.125
    wave_max : 1.9
    spectral_bin_width: "!OBS.dispersion"

  computing :
    preload_field_of_views : True

---
### default instrument parameters
object: instrument
alias: INST
name: MOSAIC_instrument_parameters
description: instrument parameters common to all MOSAIC modes

properties:
  decouple_detector_from_sky_headers: True
