# name: micado_sci_default
# description: default observation parameters for MICADO-Sci
# author : Kieran Leschinski
# date_created : 2020-07-09
# date_modified : 2020-08-17

object : configuration
alias : OBS
name : MICADO_sci_default_configuration
description : default parameters needed for a MICADO-Sci simulation

packages :
- MICADO

yamls :
- MICADO_ETC.yaml

properties :
  modes : ["SCAO", "IMG_4mas"]
  dit : 60
  ndit : 1
  airmass : 1.2
  pupil_angle : 0

---

### default simulation parameters needed for a MICADO simulation
object : simulation
alias : SIM
name : MICADO_sci_simulation_paramters
description : RC simulation paramters which need to change for a MICADO-Sci run

properties :
  random :
    seed : 9001

  spectral :
    wave_min : 0.7
    wave_mid : 1.6
    wave_max : 2.5
    spectral_resolution : 0.001

  computing :
    preload_field_of_view : True
