### default observation parameters needed for a MICADO simulation
object : configuration
alias : OBS
name : MICADO_default_configuration
description : default parameters needed for a MICADO simulation

packages :
- Armazones
- ELT
- MAORY
- MICADO

yamls :
- Armazones.yaml
- ELT.yaml
- MICADO.yaml
- MICADO_H4RG.yaml

properties :
  modes : ["SCAO", "IMG_4mas"]
  airmass : 1.2
  declination : -30
  hour_angle : 0
  pupil_angle : 0
  dit : 60
  ndit : 1

mode_yamls :
- object : instrument
  alias: OBS
  name : SCAO
  description : "SCAO optical system"
  yamls :
  - MICADO_Standalone_RO.yaml

- object : instrument
  alias: OBS
  name : MCAO
  description : "MCAO optical system"
  yamls :
  - MAORY.yaml

- object : observation
  alias: OBS
  name : IMG_4mas
  description : "wide-field imager  : 4mas/pix"
  yamls :
  - MICADO_IMG_wide.yaml
  properties :
    filter_name : Ks

- object : observation
  alias: OBS
  name : IMG_1.5mas
  description : "high resolution imager  : 1.5mas/pix"
  yamls :
  - MICADO_IMG_zoom.yaml
  properties :
    filter_name  : Ks

- object : observation
  alias: OBS
  name : IMG_HCI
  description : "High contrast imaging"
  yamls :
  - MICADO_IMG_HCI.yaml

- object : observation
  alias: OBS
  name : SPEC_15000x50
  description : "spectrograph  : slit size 15000x50mas"
  yamls :
  - MICADO_SPEC.yaml
  properties :
    trace_file : TRACE_15arcsec.fits
    slit_file : MASK_slit_15000x50.dat
    filter_name : Spec_HK

- object : observation
  alias: OBS
  name : SPEC_3000x50
  description : "spectrograph  : slit size 3000x50mas"
  yamls :
  - MICADO_SPEC.yaml
  properties :
    trace_file : TRACE_3arcsec.fits
    slit_file : MASK_slit_3000x50.dat
    filter_name : Spec_HK

- object : observation
  alias: OBS
  name : SPEC_3000x20
  description : "spectrograph  : slit size 3000x20mas"
  yamls :
  - MICADO_SPEC.yaml
  properties :
    trace_file : TRACE_3arcsec.fits
    slit_file : MASK_slit_3000x20.dat
    filter_name : Spec_HK


---
### default simulation parameters needed for a MICADO simulation
object : simulation
alias : SIM
name : MICADO_simulation_paramters
description : RC simulation paramters which need to change for a MICADO run

properties :
  random :
    seed : 9001

  spectral :
    wave_min : 0.7
    wave_mid : 1.6
    wave_max : 2.5
    
  computing : 
    preload_field_of_view : True

  reports:
    preamble_file: "../docs/preamble.rst"
