### default observation parameters needed for a MICADO simulation
object : configuration
alias : OBS
name : MICADO_default_configuration
description : default parameters needed for a MICADO simulation

packages:
- Armazones
- ELT
- MAORY
- MICADO

yamls:
- Armazones.yaml
- ELT.yaml
- MICADO.yaml
- MICADO_Standalone_RO.yaml
- MICADO_IMG_wide.yaml
- MICADO_H4RG.yaml

properties :
  filter_name : TC_filter_Ks.dat
  airmass : 1.2
  declination : -30
  hour_angle : 0
  pupil_angle : 0


---
### default simulation parameters needed for a MICADO simulation
object : simulation
alias : SIM
name : MICADO_simulation_paramters
description : RC simulation paramters which need to change for a MICADO run

properties :
  random :
    seed : 9001

  spectral :
    wave_min : 0.7
    wave_mid : 1.6
    wave_max : 2.5

---
### default parameters for Armazones
object : atmosphere
alias : ATMO
name : default_armazones_conditions

properties :
  pwv : 2.5       # mm
  temperature : 9 # deg C
  humidity : 25   # %
  pressure: 750   # millibar



