---
### default observation parameters needed for a MICADO simulation

object : configuration
alias : OBS
name : MICADO_default_configuration
description : default parameters needed for a MICADO simulation
date_modified: 2023-07-13
changes:
  - 2023-07-13 (OC) add modes for FDR slits, deprecate pre-FDR slits

packages :
- Armazones
- ELT
- MORFEO
- MICADO

yamls :
- Armazones.yaml
- ELT.yaml
- MICADO.yaml
- DREAMS_InGaAs.yaml

properties :
  instrument : MICADO
  modes : ["SCAO", "IMG_4mas"]
  airmass : 1.2
  declination : -30
  hour_angle : 0
  pupil_angle : 0
  dit : 60
  ndit : 1
  catg : SCIENCE
  tech : IMAGE
  type : OBJECT
  # Should be datetimes, but is copied verbatim, so should work.
  mjdobs : "2022-05-04T02:30:00"
  tplstart : "2022-05-04T02:30:00"
  tplexpno : 0
  tplno : 0
  obsname : "MyScienceTest"
  ra : 0.0
  dec : 0.0

mode_yamls :
- object : instrument
  alias: OBS
  name : SCAO
  description : "SCAO optical system"
  yamls :
  - MICADO_Standalone_RO.yaml

- object : observation
  alias: OBS
  name : IMG_4mas
  description : "wide-field imager  : 4mas/pix"
  yamls :
  - MICADO_IMG_wide.yaml
  properties :
    filter_name_fw1: open
    filter_name_fw2: Ks
    filter_name_pupil: open

---
### default simulation parameters needed for a MICADO simulation
object : simulation
alias : SIM
name : MICADO_simulation_paramters
description : RC simulation paramters which need to change for a MICADO run

properties :
  random :
    seed : 9001

  spectral :
    wave_min : 0.7
    wave_mid : 1.6
    wave_max : 2.5

  computing :
    preload_field_of_views : True

  reports:
    preamble_file: "../docs/micado.rst"
