---
### default observation parameters needed for a MICADO simulation

object: configuration
alias: OBS
name: MICADO_default_configuration
description: default parameters needed for a MICADO simulation
status: development
needs_scopesim: "v0.10.0b4"
date_modified: 2025-10-09
changes:
  - 2023-07-13 (OC) add modes for FDR slits, deprecate pre-FDR slits
  - 2025-06-27 (FH) add needs_scopesim keyword
  - 2025-10-09 (OC) proper MJD value

packages:
- Armazones
- ELT
- MORFEO
- MICADO

yamls:
- Armazones.yaml
- ELT.yaml
- MICADO.yaml
- MICADO_H4RG.yaml

properties :
  instrument : MICADO
  modes : ["SCAO", "IMG_4mas"]
  airmass : 1.2
  declination : -30
  hour_angle : 0
  pupil_angle : 0
  dit : 60
  ndit : 1
  catg : SCIENCE
  tech : IMAGE
  type : OBJECT
  # Should be datetimes, but is copied verbatim, so should work.
  mjdobs : 61529.104
  tplstart : "2022-05-04T02:30:00"
  tplexpno : 0
  tplno : 0
  obsname : "MyScienceTest"
  ra : 0.0
  dec : 0.0

mode_yamls :
- object : instrument
  alias: OBS
  name : SCAO
  description : "SCAO optical system"
  yamls :
  - MICADO_Standalone_RO.yaml

- object : instrument
  alias: OBS
  name : MCAO
  description : "MCAO optical system"
  yamls :
  - MORFEO.yaml

- object : observation
  alias: OBS
  name : IMG_4mas
  description : "wide-field imager  : 4mas/pix"
  status: development
  yamls :
  - MICADO_IMG_wide.yaml
  properties :
    filter_name_fw1: open
    filter_name_fw2: Ks
    filter_name_pupil: open

- object : observation
  alias: OBS
  name : IMG_1.5mas
  description : "high resolution imager  : 1.5mas/pix"
  status: development
  yamls :
  - MICADO_IMG_zoom.yaml
  properties :
    filter_name_fw1: open
    filter_name_fw2: Ks
    filter_name_pupil: open

- object : observation
  alias: OBS
  name : IMG_HCI
  description : "High contrast imaging"
  status: experimental
  yamls :
  - MICADO_IMG_HCI.yaml

- object : observation
  alias: OBS
  name : SPEC_15000x20
  description : "spectrograph : slit size 15000x20mas"
  status: development
  yamls :
  - MICADO_SPEC.yaml
  properties :
    trace_file : TRACE_MICADO.fits
    slit_file : MASK_slit_15000x20.dat
    filter_name_fw1: Spec_HK
    filter_name_fw2: open
    filter_name_pupil: open

- object : observation
  alias: OBS
  name : SPEC_3000x48
  description : "spectrograph : slit size 3000x48mas"
  status: development
  yamls :
  - MICADO_SPEC.yaml
  properties :
    trace_file : TRACE_MICADO.fits
    slit_file : MASK_slit_3000x48.dat
    filter_name_fw1: Spec_HK
    filter_name_fw2: open
    filter_name_pupil: open

- object : observation
  alias : OBS
  name : SPEC_3000x16
  description : "spectrograph : slit size 3000x16mas"
  status: development
  yamls :
  - MICADO_SPEC.yaml
  properties :
    trace_file : TRACE_MICADO.fits
    slit_file : MASK_slit_3000x16.dat
    filter_name_fw1 : Spec_IJ
    filter_name_fw2 : open
    filter_name_pupil : open

- object : observation
  alias: OBS
  name : SPEC_15000x50
  description : "spectrograph : slit size 15000x50mas"
  status: deprecated
  deprecate : "Deprecated instrument mode. For spectroscopy use
  - SPEC_3000x16
  - SPEC_3000x48
  - SPEC_15000x20"
  yamls :
  - MICADO_SPEC.yaml
  properties :
    trace_file : TRACE_MICADO.fits
    slit_file : MASK_slit_15000x50.dat
    filter_name_fw1: Spec_HK
    filter_name_fw2: open
    filter_name_pupil: open

- object : observation
  alias: OBS
  name : SPEC_3000x50
  description : "spectrograph : slit size 3000x50mas"
  status: deprecated
  deprecate : "Deprecated instrument mode. For spectroscopy use
  - SPEC_3000x16
  - SPEC_3000x48
  - SPEC_15000x20"
  yamls :
  - MICADO_SPEC.yaml
  properties :
    trace_file : TRACE_MICADO.fits
    slit_file : MASK_slit_3000x50.dat
    filter_name_fw1: Spec_HK
    filter_name_fw2: open
    filter_name_pupil: open

- object : observation
  alias: OBS
  name : SPEC_3000x20
  description : "spectrograph : slit size 3000x20mas"
  status: deprecated
  deprecate : "Deprecated instrument mode. For spectroscopy use
  - SPEC_3000x16
  - SPEC_3000x48
  - SPEC_15000x20"
  yamls :
  - MICADO_SPEC.yaml
  properties :
    trace_file : TRACE_MICADO.fits
    slit_file : MASK_slit_3000x20.dat
    filter_name_fw1: Spec_HK
    filter_name_fw2: open
    filter_name_pupil: open


---
### default simulation parameters needed for a MICADO simulation
object : simulation
alias : SIM
name : MICADO_simulation_paramters
description : RC simulation paramters which need to change for a MICADO run

properties :
  random :
    seed : 9001

  spectral :
    wave_min : 0.7
    wave_mid : 1.6
    wave_max : 2.5

  computing :
    preload_field_of_views : True

  reports:
    preamble_file: "../docs/micado.rst"
