---
### default configuration for METIS simulations using the WCU

object: configuration
alias: OBS
name: METIS_WCU_default_configuration
description: default parameters and mode definitions for METIS/WCU
date_modified: 2024-09-03
changes:
  - 2024-09-03 (OC) file created

packages:
  - METIS_WCU
  - METIS

yamls:
  - METIS_WCU.yaml
  - METIS.yaml          # applies to all modes

properties:
  instrument: "METIS_WCU"
  modes: ["img_lm"]
  exptime: 1.
  dit: 1              # when exptime is given and auto_exposure is on,
  ndit: 1             # these values are ignored
  pupil_transmission: 1.0   # this is for the cold stop, should not be here

  # Default DPR keywords and template name.
  # TODO: add those later

mode_yamls:
  - object: calibration
    alias: OBS     # or CAL?
    name: img_lm
    description: "METIS LM-band imaging with WCU"
    yamls:
      - METIS_IMG_LM.yaml
      - METIS_DET_IMG_LM.yaml
    properties:
      psf_file: PSF_SCAO_9mag_06seeing.fits   # TODO: change
      filter_name: Lp
      nd_filter_name: open
      slit: false
      adc: false
      detector_readout_mode: fast

  - object: calibration
    alias: OBS    # or CAL?
    name: img_n
    description: "METIS N-band imaging with WCU"
    yamls:
      - METIS_IMG_N.yaml
      - METIS_DET_IMG_N_GeoSnap.yaml
    properties:
      psf_file: PSF_SCAO_9mag_06seeing.fits
      filter_name: N2
      nd_filter_name: open
      slit: false
      adc: false
      chop_offsets: None   # TODO: can we use this to turn of the ChopNodder?
      nod_offsets: None
      detector_readout_mode: high_capacity

  ### Define LSS and LMS modes

---
### default simulation parameters needed for a METIS simulation
# TODO: These appear here and in METIS/defaults.yaml
object: simulation
alias: SIM
name: METIS_simulation_parameters
description: RC simulation parameters which need to change for a METIS run

properties:
  random:
    seed: None            # 9001

  spectral:
    wave_min: 2.85
    wave_mid: 8.425
    wave_max: 14.0

  computing:
    spline_order: 1
    preload_field_of_views: True
