name: Tests dev
on:
  push:
    branches:
      - dev_master

  # Runs at 05:00 UTC, Monday through Friday
  schedule:
    - cron: "0 5 * * MON-FRI"

jobs:
  tests:
    name: Tests
    uses: ./.github/workflows/tests.yml

  internal_tests:
    name: Internal Tests
    uses: ./.github/workflows/internal_tests.yml

  notebook_tests:
    name: Notebook tests
    uses: ./.github/workflows/notebooktests.yml

  badge_report:
    name: Badge Report
    uses: ./.github/workflows/badge_report.yml
