---
### default observation parameters needed for a HAWKI simulation
alias: PKG
name: HAWKI_default_configuration
description: default parameters needed for a HAWKI simulation
status: experimental
date_modified: 2024-12-12
changes:
  - 2019-08-14 (KL) initial creation
  - 2022-02-22 (MV) formatting
  - 2024-11-19 (FH) add status keywords
  - 2024-12-12 (FH) restructure default OBS properties, add PKG alias

packages:
  - Paranal
  - VLT
  - HAWKI

yamls:
  - Paranal.yaml
  - VLT.yaml
  - HAWKI.yaml
  - HAWKI_H2RG.yaml

---
### default observation parameters needed for a HAWKI simulation
alias: OBS
properties:
  filter_name: Ks
  airmass: 1.2
  declination: -30
  hour_angle: 0
  pupil_angle: 0
  dit: 60  # [s]
  ndit: 1

---
### default simulation parameters needed for a HAWKI simulation
alias: SIM
properties:
  random:
    seed: 9001

  spectral:
    wave_min: 0.85  # [um]
    wave_mid: 1.6   # [um]
    wave_max: 2.5   # [um]
